# Generated by Django 5.2.7 on 2025-10-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='last_phone',
            new_name='phone',
        ),
    ]
